# Project: ProjetoTestes
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = obj/Teste_Main.o
LINKOBJ  = obj/Teste_Main.o
LIBS     = -L"C:/Users/Programador/Desktop/ProjetoFinal/Testes/lib" lib/libgtest.a
INCS     = -I"C:/Users/Programador/Desktop/ProjetoFinal/Testes/include" -I"C:/Users/Programador/Desktop/ProjetoFinal/Testes/include/gtest" -I"C:/Users/Programador/Desktop/ProjetoFinal/Testes/include/gtest/internal"
CXXINCS  = -I"C:/Users/Programador/Desktop/ProjetoFinal/Testes/include" -I"C:/Users/Programador/Desktop/ProjetoFinal/Testes/include/gtest" -I"C:/Users/Programador/Desktop/ProjetoFinal/Testes/include/gtest/internal"
BIN      = ProjetoTestes.exe
CXXFLAGS = $(CXXINCS) -pthread
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

obj/Teste_Main.o: src/Teste_Main.c
	$(CPP) -c src/Teste_Main.c -o obj/Teste_Main.o $(CXXFLAGS)
