#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG1                             100
#define IDD_DIALOG2                             111
#define IDD_TABPROP                             113
#define IDD_TABVEIC                             115
#define IDD_TABMANUN                            117
#define IDD_PROP_ADD_FORM                       128
#define IDD_PROP_ALTERAR                        130
#define IDD_PROP_ALTERAR_FORM                   134
#define IDD_PROP_EXCLUIR                        138
#define IDD_PROP_EXCLUIR_FORM                   140
#define IDD_CREDITOS                            143
#define IDD_VEIC_ADD_FORM                       145
#define IDD_PEGACPF_VEIC                        147
#define IDD_VEIC_ALTERAR                        149
#define IDD_VEIC_ALTERAR_FORM                   151
#define IDD_VEIC_EXCLUIR                        153
#define IDD_VEIC_EXCLUIR_FORM                   155
#define IDD_MANUT_ADD_FORM                      157
#define IDD_PROP_APRESENTAR                     161
#define IDD_MANUT_EXCLUIR_FORM                  170
#define IDD_MANUT_DADOS_FORM                    172
#define IDD_MANUT_DADOS                         173
#define IDD_PROP_MOSTRA_VEIC                    175
#define IDD_MOSTRA_TODOS_DADOS                  177
#define IDB_TESTE                               179
#define IDI_ICON_PROJETO                        181
#define ID_BOTAO_ACAO_VEIC                      40000
#define ID_BOTAO_APRESENTAR_PROP                40000
#define ID_BOTAO_EXCLUIR_MANUT                  40000
#define ID_BOTAO_PROP_MANUT_VEIC                40000
#define ID_EDIT_PLACA_MANUT                     40000
#define ID_MANUT_DATA_INICIO                    40000
#define ID_MOSTRA_DADOS_TREE_VIEW               40000
#define ID_NUVEM_BOTAO                          40000
#define ID_PEGACPF_CANCEL                       40000
#define ID_PROP_LIST                            40000
#define ID_PROP_MOSTRA_BUSCA_EDIT               40000
#define ID_VEIC_ALTERAR_BUSCA_EDIT              40000
#define ID_BOTAO_ADD_MANUT                      40001
#define ID_BOTAO_ALTERAR_VEIC                   40001
#define ID_BOTAO_APRESENTAR_TUDO                40001
#define ID_BOTAO_APRESENTAR_VEIC_PROP           40001
#define ID_EDIT_CPF_MANUT                       40001
#define ID_MANUT_DATA_FIM                       40001
#define ID_PEGACPF_CAMPO                        40001
#define ID_PROP_MOSTRA_VEIC_LIST                40001
#define ID_VEIC_ADD_LOG                         40001
#define ID_VEIC_ALTERAR_LIST                    40001
#define ID_VEIC_EXCLUIR_BUSCA_EDIT              40001
#define ID_BOTAO_PESQUISAR_MANUT                40002
#define ID_CREDITOS_BOTAO                       40002
#define ID_EDIT_PECAS_MANUT                     40002
#define ID_MANUT_LIST                           40002
#define ID_PEGACPF_LOG                          40002
#define ID_PROP_VER_DADOS_BOTAO                 40002
#define ID_VEIC_ALTERAR_BOTAO                   40002
#define ID_VEIC_EXCLUIR_ATUALIZAR_BOTAO         40002
#define ID_EDIT_MODELO_VEIC                     40003
#define ID_EDIT_OBRA_MANUT                      40003
#define ID_PEGACPF_OK                           40003
#define ID_PROP_MOSTRAR_ATUALIZAR_BOTAO         40003
#define ID_VEIC_ALTERAR_ATUALIZAR_BOTAO         40003
#define ID_VEIC_EXCLUIR_LIST                    40003
#define ID_EDIT_DESCRICAO_MANUT                 40004
#define ID_EDIT_NOME_PROP                       40004
#define ID_MANUT_BOTAO_LIMPAR                   40004
#define ID_VEIC_EXCLUIR_BOTAO                   40004
#define ID_BOTAO_ACAO_MANUT                     40005
#define ID_BOTAO_SAIR_MANUT                     40005
#define ID_GIF_CREDITOS                         40005
#define ID_MANUT_ADD_LOG                        40006
#define ID_MANUT_BOTAO_VER_DADOS                40006
#define ID_PROP_ALTERAR_BUSCA_EDIT              40006
#define HTAB                                    40007
#define ID_BOTAO_CANCELAR_MANUT                 40007
#define ID_BOTAO_ADD_VEIC                       40008
#define ID_BOTAO_CANCELAR_VEIC                  40008
#define ID_EDIT_CPF_PROP                        40009
#define ID_EDIT_FAB_VEIC                        40010
#define ID_GIF_CREDITOS_2                       40011
#define ID_PROP_ALTERAR_LIST                    40012
#define ID_BOTAO_ALTERAR_PROP                   40013
#define ID_BOTAO_EXCLUIR_VEIC                   40014
#define ID_EDIT_CIDADE_PROP                     40015
#define ID_PROP_ALTERAR_BOTAO                   40017
#define ID_EDIT_ESTADO_PROP                     40019
#define ID_EDIT_PLACA_VEIC                      40020
#define ID_PROP_ALTERAR_ATUALIZAR_BOTAO         40021
#define ID_BOTAO_EXCLUIR_PROP                   40022
#define ID_EDIT_CHASSI_VEIC                     40023
#define ID_EDIT_DESCRICAO_PROP                  40025
#define ID_EDIT_ANO_VEIC                        40026
#define ID_EDIT_TELEFONE_PROP                   40027
#define ID_Sair                                 40028
#define ID_BOTAO_ACAO_PROP                      40029
#define ID_GROUPBOX_PROP                        40030
#define OFICIAL_ENDERECO                        40031
#define ID_BOTAO_CANCELAR_PROP                  40032
#define ID_PROP_ADD_LOG                         40034
#define OFIC_ENDER                              40035
#define ID_BOTAO_ADD_PROP                       40036
#define ID_Entrar                               40037
#define OFICIAL_NOME                            40038
#define OFIC_NOME                               40039
